comment: false

coverage:
  status:
    project:
      default: false
      unit:
        target: auto
        flags:
          - unit
      integration:
        target: auto
        flags:
          - integration
    patch:
      default:
        target: 90%
      flags:
        - unit
