name = "ParticleInCell"
uuid = "3f496205-d90f-4778-83b9-652c261f54b9"
authors = ["Luke Adams <luke@lukeclydeadams.com> and contributors"]
version = "1.0.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"

[compat]
FFTW = "1"
LinearSolve = "2.9"
SparseArrays = "1.9"
StaticArrays = "1"
StructEquality = "2"
julia = "1.9"
