name = "ParticleInCell2"
uuid = "3f496205-d90f-4778-83b9-652c261f54b9"
authors = ["Luke Adams <luke@lukeclydeadams.com> and contributors"]
version = "1.0.0-DEV"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"

[compat]
FFTW = "1"
StaticArrays = "1"
StructEquality = "2"
julia = "1.9"
