name = "ParticleInCell2"
uuid = "3f496205-d90f-4778-83b9-652c261f54b9"
authors = ["Luke Adams <luke@lukeclydeadams.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
